// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Hermes")]
[assembly: AssemblyDescriptionAttribute("Elders.Hermes - Unique Id generator")]
[assembly: GuidAttribute("e53468fd-9f29-422c-9499-28e516aa41b1")]
[assembly: AssemblyProductAttribute("Elders.Hermes")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
